site_name: ZF2 AutoTable
theme: readthedocs
docs_dir: code
site_dir: ../docs
pages:
- Home: index.md
- Installation: install.md
- Retrieve Records: retrieving.md
- Save Records: saving.md
- Configuration: config.md
- Codebase Integration: codebase-integration.md
